server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false

# Configuración para Railway/Render con PostgreSQL
---
spring:
  config:
    activate:
      on-profile: railway
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

# Configuración de seguridad para producción
app:
  demo:
    username: ${DEMO_USERNAME:demo}
    password: ${DEMO_PASSWORD:demo123}
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}

logging:
  level:
    com.facturacion.electronica: INFO
    org.springframework.security: WARN
    org.hibernate: WARN