server:
  port: 8080
  servlet:
    session:
      timeout: 10m # 10 minutos de timeout de sesión

spring:
  application:
    name: sistema-facturacion-electronica
  
  # Base de datos
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  
  # H2 Console (solo para desarrollo)
  h2:
    console:
      enabled: true
      path: /h2-console

# Configuración SUNAT
sunat:
  # URLs de servicios SUNAT (Beta)
  urls:
    beta:
      factura: https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService
      consulta: https://e-beta.sunat.gob.pe/ol-ti-itcpqfegem-beta/billConsultService
    produccion:
      factura: https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService
      consulta: https://e-factura.sunat.gob.pe/ol-ti-itcpqfegem/billConsultService
  
  # Configuración de empresa
  empresa:
    ruc: "20000000000"  # RUC de ejemplo
    usuario: "USUARIO"  # Usuario SOL
    clave: "CLAVE"      # Clave SOL
    
  # Configuración de certificado
  certificado:
    ruta: "certificados/certificado.p12"
    clave: "password"
    alias: "alias"

# Configuración de logging
logging:
  level:
    '[com.facturacion.electronica]': DEBUG
    '[org.springframework.web]': DEBUG
  file:
    name: logs/facturacion-electronica.log

# Configuración de documentación API
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html